kind: CronJob
apiVersion: batch/v1
metadata:
  name: ora2pg-delta
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: ora2pg-data-today-vol
              persistentVolumeClaim:
                claimName: ora2pg-test-today
            - name: ora2pg-data-yesterday-vol
              persistentVolumeClaim:
                claimName: ora2pg-test-yesterday
          containers:
            - name: ora2pg-vol
              image: >-
                image-registry.openshift-image-registry.svc:5000/78c88a-tools/ora2pg-delta:latest
              env:
                - name: DIR_TODAY
                  valueFrom:
                    secretKeyRef:
                      name: ora2pg-delta
                      key: DIR_TODAY
                - name: DIR_YESTERDAY
                  valueFrom:
                    secretKeyRef:
                      name: ora2pg-delta
                      key: DIR_YESTERDAY
                - name: CLEAN_DIRS
                  valueFrom:
                    secretKeyRef:
                      name: ora2pg-delta
                      key: CLEAN_DIRS
                - name: CHUNK_SIZE
                  valueFrom:
                    secretKeyRef:
                      name: ora2pg-delta
                      key: CHUNK_SIZE
              resources:
                limits:
                  cpu: '1'
                  memory: 5Gi
                requests:
                  cpu: 200m
                  memory: 3Gi
              volumeMounts:
                - name: ora2pg-data-today-vol
                  mountPath: /data/
                - name: ora2pg-data-yesterday-vol
                  mountPath: /data-yesterday/
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
